services:
  app:
    build:
      context: .
      dockerfile: service/auth_service/Dockerfile
      args:
        - target=dev
    image: ats-auth
    environment:
      ENV: dev
      PORT: 8080
      DB_USER: auth
      DB_PASSWORD: 1234
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_NAME: auth
      REDIS_HOST: ats-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    volumes:
      - .:/project
    ports:
      - "10001:8080"
    working_dir: /project/service/auth_service
  auth-db:
    image: mysql:8.0.33
    platform: linux/arm64
    container_name: auth-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: auth
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: auth
    volumes:
      - auth-db-data:/var/lib/mysql
      - $PWD/migration/auth/conf.d:/etc/mysql/conf.d
    ports:
      - "20001:3306"
  ats-redis:
    image: "redis:latest"
    container_name: ats-redis
    ports:
      - "30001:6379"
    volumes:
        - redis-data:/data

volumes:
  auth-db-data:
  redis-data: