services:
  app:
    build:
      context: .
      dockerfile: service/auth_service/Dockerfile
      args:
        - target=dev
    image: ats-auth
    environment:
      DB_USER: root
      DB_PASSWORD: 1234
      DB_HOST: host.docker.internal:3306
      DB_NAME: auth
      REDIS_HOST: host.docker.internal:6379
      REDIS_PASSWORD: ""
    volumes:
      - .:/project
    ports:
      - "10001:80"
    working_dir: /project/service/auth_service