name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.24'
    - name: Set up environment file for auth_service
      run: cp service/auth_service/.env.example service/auth_service/.env
    - run: go test ./service/auth_service/... -coverprofile=coverage.out
    - name: report coverage
      uses: k1LoW/octocov-action@v0
